### ISSUE TITLE
在chrome中执行点击操作之后无反应

### ISSUE THREAD

**Issue by Parsifa1** [Honoka55/hrbeu-credit-statistics#2]
# 基本信息
版本：0.24
环境：google chrome + violentmonkey

# 尝试
在edge中使用相同的环境之后能够正常工作

# 猜想
可能是chrome本身的问题（大雾
学姐加油喵）

**Comment by Honoka55** [comment]
未能复现，似乎是POST方法跨域请求部分的代码有问题 @jht3QAQ

**Comment by Honoka55** [comment]
经复现系POST请求跳转至统一身份认证页面导致无结果

**Comment by jht3QAQ** [comment]
麻烦提供一下chrome版本和violentmonkey版本

**Comment by Parsifa1** [comment]
chrome: 110.0.5481.180
violentmonkey :2.14.0

**Comment by jht3QAQ** [comment]
由于chrome不提供历史版本
我在chromium 110.0.5481.0 violentmonkey 2.14.0环境中复现失败
